---
title: "Act 4 Field"
author: "Krissa Joy L. Tabornal"
date: "10/4/2021"
output: pdf_document
---

```{r}

library(tidyverse)
event <- read_csv("D:/kaya/Documents/2 SY 2021-2022/1st Semester 2021-2022/Bio 115 - Field Biology/Laboratory/Wk 3/FieldBio_Act4/event.csv")
emof <- read_csv("D:/kaya/Documents/2 SY 2021-2022/1st Semester 2021-2022/Bio 115 - Field Biology/Laboratory/Wk 3/FieldBio_Act4/emof.csv")
occurrence <- read_csv("D:/kaya/Documents/2 SY 2021-2022/1st Semester 2021-2022/Bio 115 - Field Biology/Laboratory/Wk 3/FieldBio_Act4/occurrence.csv")
```

```{r}
newoccurrence <- occurrence %>%
                  select(occurrenceID, organismQuantityType, scientificName, family, genus, order, individualCount)

benthic <- emof %>%
        filter(str_detect(measurementID, "benthic")) %>%
        filter(!str_detect(measurementID, "T09")) %>%
        filter(!str_detect(measurementID, "T10")) %>%
        select(measurementID, measurementType, measurementValue) %>%
  separate(col = measurementID, into = c("Location", "Transect", "Date", "Benthic", "Type"), sep = ":") 

benthicfinal <- benthic %>%
            select(Transect, measurementType, measurementValue) %>% mutate(cover = as.numeric(measurementValue)/100)

livecoral <- benthicfinal %>%
          filter(str_detect(measurementType, "Branching|Massive|Encrusting|Millepora| Submassive|Soft"), negate = TRUE)

totalcover <-livecoral %>%
              spread(key = Transect, value = cover) 


transect <- c("T01", "T02", "T03", "T04", "T05", "T06", "T07", "T08")
Totalcover <- c(0.3663, 0.6039, 0.5148, 0.0792, 0.0891, 0.5149, 0.2772, 0.3366)
covertotal<-data.frame(transect, Totalcover)
  
fish <- newoccurrence %>%
      filter(str_detect(occurrenceID, "fish"))

fishfinal <- fish %>%
  select(occurrenceID, organismQuantityType, scientificName, individualCount) %>%
  separate(col = occurrenceID, into = c("Location", "Transect", "Date", "Benthic", "Species"), sep = ":") %>%
  select(Transect, Species, organismQuantityType, individualCount)

fishcount <- fishfinal %>%
      spread(key = Transect, value = individualCount) %>%
      mutate_if(is.integer, as.numeric) 

fishtotal <- data.frame(colSums(Filter(is.numeric,fishcount), na.rm = TRUE))
transects <- c("T01", "T02", "T03", "T04", "T05", "T06", "T07", "T08")
fishabundance <- c(286, 280, 488, 445, 248, 72, 36, 241)  
totalfish <- data.frame(transects, fishabundance)

coralfish <- data.frame(totalfish, covertotal)
```

% cover per transect
```{r}
ggplot()+ geom_col(data = benthicfinal, aes(x = Transect, y = cover, fill = measurementType), position = "fill") + labs(y = "Percent Cover", fill = "Type")

ggplot()+ geom_col(data = livecoral, aes(x = Transect, y = cover, fill = measurementType), position = "fill") + labs(y = "Percent Cover", fill = "Type of Live Coral")

ggplot(data = totalfish, aes(x = transects, y = fishabundance)) + geom_col() + labs (x = "Transect", y = "Fish Abundance")

ggplot(data = covertotal, aes(x = transect, y = Totalcover)) + geom_col() + labs (x = "Transect", y = "Live Coral Cover")

ggplot(data = coralfish, aes(x = Totalcover, y = fishabundance), fill = transect) + geom_point(size = 4) + labs(x = "Live Coral Cover", y = "Fish Abundance") + theme_classic()
```

plankton biodiversity
```{r}
plankton <- newoccurrence %>%
      filter(str_detect(occurrenceID, "phytoplankton"))

phytoplankton <- plankton %>%
  select(occurrenceID, organismQuantityType, scientificName, individualCount) %>%
  separate(col = occurrenceID, into = c("Location", "Site", "Date", "Benthic", "Species"), sep = ":") %>%
  select(Site, Species, organismQuantityType, individualCount)

ggplot(phytoplankton, aes(x=as.factor(Site), fill=as.factor(Species) )) + 
    geom_bar( ) + theme_classic() +
    theme(legend.position="none") + labs(y = "Site", x = "Species Count", title = "Phytoplankton species count across sites" ) + coord_flip() 

phytoplanktonNew <- phytoplankton %>%
  select(Site,Species,individualCount) %>%
  group_by(Species, Site)

planktonwide <- phytoplanktonNew %>% pivot_wider(names_from = Species, values_from = individualCount, Site)

planktonwide[planktonwide == "NULL"] <- NA


```


```{r}
library(readxl)
library(vegan)
Diversity <- read_excel("D:/kaya/Documents/2 SY 2021-2022/1st Semester 2021-2022/Bio 115 - Field Biology/Laboratory/Wk 3/FieldBio_Act4/Diversity.xlsx", 
    sheet = "Sheet2")

diversity_results <- diversity(x = Diversity,index = "shannon")
spa <- specaccum(Diversity)
plot(spa)
```


